/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package capaPresentacion;

import java.util.ArrayList;

/**
 *
 * @author Raúl
 */
public class PantallaNuevaPartida extends javax.swing.JFrame {


    private ControladorPresentacion CP = ControladorPresentacion.getInstance();
    private ArrayList<String> listaKakuros;


    /**
     * Creates new form PantallaNuevaPartida
     */
    public PantallaNuevaPartida() {
        listaKakuros = CP.previewKakuro();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupoBotonesModo = new javax.swing.ButtonGroup();
        GrupoBotonesNivel = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        NivelMucho = new javax.swing.JRadioButton();
        NivelMedio = new javax.swing.JRadioButton();
        NivelPoco = new javax.swing.JRadioButton();
        NivelNada = new javax.swing.JRadioButton();
        ModoNormal = new javax.swing.JRadioButton();
        ModoRanking = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Volver atrás");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });


        jLabel1.setText("Kakuros disponibles");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings =  listaKakuros.toArray(new String[0]);
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jLabel2.setText("Nivel de ayuda");

        jLabel3.setText("Modo de juego");

        GrupoBotonesNivel.add(NivelMucho);
        NivelMucho.setSelected(true);
        NivelMucho.setText("Mucho");

        GrupoBotonesNivel.add(NivelMedio);
        NivelMedio.setText("Medio");
        NivelMedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NivelMedioActionPerformed(evt);
            }
        });

        GrupoBotonesNivel.add(NivelPoco);
        NivelPoco.setText("Poco");

        GrupoBotonesNivel.add(NivelNada);
        NivelNada.setText("Nada");

        GrupoBotonesModo.add(ModoNormal);
        ModoNormal.setSelected(true);
        ModoNormal.setText("Normal");

        GrupoBotonesModo.add(ModoRanking);
        ModoRanking.setText("Ranking 👑");
        ModoRanking.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                ModoRankingStateChanged(evt);
            }
        });

        jButton2.setText("Empezar la partida");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150
                        , javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(NivelMucho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(NivelMedio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(NivelPoco, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(NivelNada, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ModoNormal, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ModoRanking, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ModoNormal)
                            .addComponent(NivelMucho, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(NivelMedio)
                                    .addComponent(ModoRanking))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NivelPoco)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NivelNada))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    /** 
     * @param evt
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt){
        PantallaSelecionPartida vistaSelecionPartida = new PantallaSelecionPartida();
        vistaSelecionPartida.setVisible(true);
        dispose();
    }

    
    /** 
     * @param evt
     */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt){
        //launch info to CDomain 
        String modo= null;
        String nivelAyuda = null;
        String ID= null;
        String[] tamano = null;
        if(ModoNormal.isSelected()) modo = "Normal";
        else if(ModoRanking.isSelected()) modo = "Ranking";

        if(NivelNada.isSelected()) nivelAyuda = "Nada";
        else if(NivelPoco.isSelected()) nivelAyuda = "Poco";
        else if(NivelMedio.isSelected()) nivelAyuda = "Medio"; 
        else if(NivelMucho.isSelected()) nivelAyuda = "Mucho"; 

        int i = jList1.getSelectedIndex();
        if(i != -1){
            ID = listaKakuros.get(i).split(" ")[1];
            tamano = listaKakuros.get(i).split(" ")[3].split("x");
            //System.out.println(tamano[0] + ", " + tamano[1]);
            ArrayList<String> listaParam = new ArrayList<String>();
            listaParam.add(ID);
            listaParam.add(nivelAyuda);
            listaParam.add(modo);

            ArrayList<ArrayList<String>> partida = CP.crearPartida(listaParam);
            //for(ArrayList<String> a : partida){
            //    System.out.println(a);
            //}
            PantallaJugando vistaJugando = new PantallaJugando(partida,true);
            vistaJugando.setVisible(true);
            dispose();
        }
        else jLabel4.setText("Selecciona un Kakuro");
        //System.out.println(modo);
        //System.out.println(nivelAyuda);
        //System.out.println(ID);
        //TODO: linkear con la pantalla de la partida
        
    }


    
    /** 
     * @param args[]
     */
    private void NivelMedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NivelMedioActionPerformed
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_NivelMedioActionPerformed

    
    /** 
     * @param args[]
     */
    private void ModoRankingStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_ModoRankingStateChanged
        // TODO add your handling code here:
        NivelMucho.setEnabled(!ModoRanking.isSelected());
        NivelMedio.setEnabled(!ModoRanking.isSelected());
        NivelPoco.setEnabled(!ModoRanking.isSelected());
        NivelNada.setSelected(ModoRanking.isSelected());
    }//GEN-LAST:event_ModoRankingStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaNuevaPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaNuevaPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaNuevaPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaNuevaPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaNuevaPartida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup GrupoBotonesModo;
    private javax.swing.ButtonGroup GrupoBotonesNivel;
    private javax.swing.JRadioButton ModoNormal;
    private javax.swing.JRadioButton ModoRanking;
    private javax.swing.JRadioButton NivelMedio;
    private javax.swing.JRadioButton NivelMucho;
    private javax.swing.JRadioButton NivelNada;
    private javax.swing.JRadioButton NivelPoco;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
