/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package capaPresentacion;

import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JProgressBar;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import javax.swing.JDialog;
/**
 *
 * @author Raúl
 */
public class PantallaGeneracionKakuro extends javax.swing.JFrame {

    private ControladorPresentacion CP = ControladorPresentacion.getInstance();
    /**
     * Creates new form PantallaGeneracionKakuro
     */
    public PantallaGeneracionKakuro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        //JFormattedTextField field = new JFormattedTextField();
        jButton1 = new javax.swing.JButton();
        Altura = new javax.swing.JLabel();
        MaxCasillas = new javax.swing.JLabel();
        Loteria = new javax.swing.JLabel();
        Anchura = new javax.swing.JLabel();
        ValorLoteria = new javax.swing.JSlider();
        ValorAltura = new javax.swing.JFormattedTextField();
        ValorAnchura = new javax.swing.JFormattedTextField();
        ValorMaxCasillas = new javax.swing.JFormattedTextField();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ValorAltura.getDocument().addDocumentListener(new DocumentListener() {
            public void changedUpdate(DocumentEvent e) {
              warn();
            }
            public void removeUpdate(DocumentEvent e) {
              warn();
            }
            public void insertUpdate(DocumentEvent e) {
              warn();
            }
          
            public void warn() {
                jLabel1.setForeground(Color.black);
                jLabel1.setText("");
            }
          });

          ValorAnchura.getDocument().addDocumentListener(new DocumentListener() {
            public void changedUpdate(DocumentEvent e) {
              warn();
            }
            public void removeUpdate(DocumentEvent e) {
              warn();
            }
            public void insertUpdate(DocumentEvent e) {
              warn();
            }
          
            public void warn() {
                jLabel1.setForeground(Color.black);
                jLabel1.setText("");
            }
          });
          
          ValorMaxCasillas.getDocument().addDocumentListener(new DocumentListener() {
            public void changedUpdate(DocumentEvent e) {
              warn();
            }
            public void removeUpdate(DocumentEvent e) {
              warn();
            }
            public void insertUpdate(DocumentEvent e) {
              warn();
            }
          
            public void warn() {
                jLabel1.setForeground(Color.black);
                jLabel1.setText("");
            }
          });

        jButton1.setText("Generar kakuros");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });



        Altura.setText("Altura");
        Altura.setToolTipText("");

        MaxCasillas.setText("Casillas blancas máximas");

        Loteria.setText("¿Como de afortunado te sientes? (Recomendamos 2 o 3)");
        Loteria.setToolTipText("1 si eres de la FIB");
        Loteria.setName(""); // NOI18N

        Anchura.setText("Anchura");

        ValorLoteria.setMajorTickSpacing(1);
        ValorLoteria.setMaximum(9);
        ValorLoteria.setMinimum(1);
        ValorLoteria.setMinorTickSpacing(1);
        ValorLoteria.setPaintLabels(true);
        ValorLoteria.setPaintTicks(true);
        ValorLoteria.setSnapToTicks(true);
        ValorLoteria.setToolTipText("Esto afecta al rendimiento del algoritmo");
        ValorLoteria.setValue(2);
        ValorLoteria.setName("Hola"); // NOI18N

        ValorAltura.setToolTipText("");

        jButton2.setText("Volver atrás");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        ValorAltura.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#"))));
        ValorAnchura.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#"))));
        ValorMaxCasillas.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#"))));





        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ValorLoteria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Loteria, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(MaxCasillas, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ValorMaxCasillas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Altura, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Anchura, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ValorAnchura, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ValorAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Altura)
                    .addComponent(ValorAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Anchura)
                    .addComponent(ValorAnchura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MaxCasillas)
                    .addComponent(ValorMaxCasillas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(Loteria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ValorLoteria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2))
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Loteria.getAccessibleContext().setAccessibleDescription("");
        ValorLoteria.getAccessibleContext().setAccessibleName("Hola2");
        ValorLoteria.getAccessibleContext().setAccessibleDescription("Hola3");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    /** 
     * @param 2
     */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        PantallaCreacionKakuros vistaCreacion = new PantallaCreacionKakuros();
        vistaCreacion.setVisible(true);
        dispose();

    }//GEN-LAST:event_jButton2ActionPerformed

    
    /** 
     * @param 2
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String lot =Integer.toString(ValorLoteria.getValue());
        ArrayList<String> tam = new ArrayList<String>();
        if(Integer.parseInt(ValorAltura.getText()) < 2 || Integer.parseInt(ValorAnchura.getText()) < 2 ){
            ponerFallido();
            return;
        } 
        tam.add(ValorAltura.getText());
        tam.add(ValorAnchura.getText());
        String maxCasillas = ValorMaxCasillas.getText();
        //ponerCargando();
        int result = JOptionPane.showConfirmDialog(null,"¿Quieres crear el kakuro con estas propiedades?\nAviso: Para casos extremos este proceso puede ser muy tardío", "Aviso creacion",
        JOptionPane.YES_NO_OPTION,
        JOptionPane.WARNING_MESSAGE);
        if(result == JOptionPane.YES_OPTION){
            ArrayList<ArrayList<String>> kakuro = CP.crearKakuro(tam, maxCasillas, lot);
            if(kakuro.get(0).get(0).equals("0") || kakuro.get(0).get(1).equals("0")) ponerFallido();
            else ponerCreado(); 
        }


    }
    public void ponerCreado(){
        float hue = (float) 120/360;
        float sat = (float) 1.0;
        float bri = (float) 0.87;
        jLabel1.setForeground(Color.getHSBColor(hue, sat, bri));
        jLabel1.setFont(new Font(jLabel1.getFont().getFontName(),Font.PLAIN, 18));
        jLabel1.setText("Kakuro creado");
    }
    public void ponerFallido(){
        float hue = (float)0.0;
        float sat = (float)1.0;
        float bri = (float) 0.87;
        jLabel1.setForeground(Color.getHSBColor(hue, sat, bri));
        jLabel1.setFont(new Font(jLabel1.getFont().getFontName(),Font.PLAIN, 16));
        jLabel1.setText("Generación fallida");
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaGeneracionKakuro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaGeneracionKakuro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaGeneracionKakuro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaGeneracionKakuro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaGeneracionKakuro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Altura;
    private javax.swing.JLabel Anchura;
    private javax.swing.JLabel Loteria;
    private javax.swing.JLabel MaxCasillas;
    private javax.swing.JFormattedTextField ValorAltura;
    private javax.swing.JFormattedTextField ValorAnchura;
    private javax.swing.JSlider ValorLoteria;
    private javax.swing.JFormattedTextField ValorMaxCasillas;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
